// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHArz5MZjIvET2PyTr6iA6Xr2lKg79anY',
    appId: '1:521233549696:web:5c903b977dea3386fb1965',
    messagingSenderId: '521233549696',
    projectId: 'cafeshopmanagement',
    authDomain: 'cafeshopmanagement.firebaseapp.com',
    storageBucket: 'cafeshopmanagement.firebasestorage.app',
    measurementId: 'G-D1B9Z3PE5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtCWcmZidFeYARx6TC2-mdCZxN0PWudlU',
    appId: '1:521233549696:android:ef8a310c1bd3cd86fb1965',
    messagingSenderId: '521233549696',
    projectId: 'cafeshopmanagement',
    storageBucket: 'cafeshopmanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CfNuQuDDGzU_SZy9sEtJhbP_gvwCbIE',
    appId: '1:521233549696:ios:bdbbf74246142e68fb1965',
    messagingSenderId: '521233549696',
    projectId: 'cafeshopmanagement',
    storageBucket: 'cafeshopmanagement.firebasestorage.app',
    iosClientId: '521233549696-066v7orbg8k4rpfd972eltlhj2f3un34.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CfNuQuDDGzU_SZy9sEtJhbP_gvwCbIE',
    appId: '1:521233549696:ios:bdbbf74246142e68fb1965',
    messagingSenderId: '521233549696',
    projectId: 'cafeshopmanagement',
    storageBucket: 'cafeshopmanagement.firebasestorage.app',
    iosClientId: '521233549696-066v7orbg8k4rpfd972eltlhj2f3un34.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHArz5MZjIvET2PyTr6iA6Xr2lKg79anY',
    appId: '1:521233549696:web:b0eec7ee84728a0afb1965',
    messagingSenderId: '521233549696',
    projectId: 'cafeshopmanagement',
    authDomain: 'cafeshopmanagement.firebaseapp.com',
    storageBucket: 'cafeshopmanagement.firebasestorage.app',
    measurementId: 'G-8X4TVY5J8X',
  );

}